
set_property PACKAGE_PIN T10 [get_ports CA]
set_property PACKAGE_PIN R10 [get_ports CB]
set_property PACKAGE_PIN K16 [get_ports CC]
set_property PACKAGE_PIN K13 [get_ports CD]
set_property PACKAGE_PIN P15 [get_ports CE]
set_property PACKAGE_PIN T11 [get_ports CF]
set_property PACKAGE_PIN L18 [get_ports CG]
set_property PACKAGE_PIN H15 [get_ports DP]
set_property PACKAGE_PIN U13 [get_ports {AN[0]}]
set_property PACKAGE_PIN K2 [get_ports {AN[1]}]
set_property PACKAGE_PIN T14 [get_ports {AN[2]}]
set_property PACKAGE_PIN P14 [get_ports {AN[3]}]
set_property PACKAGE_PIN J14 [get_ports {AN[4]}]
set_property PACKAGE_PIN T9 [get_ports {AN[5]}]
set_property PACKAGE_PIN J18 [get_ports {AN[6]}]
set_property PACKAGE_PIN J17 [get_ports {AN[7]}]
set_property PACKAGE_PIN C17 [get_ports JA1]
#switch
set_property PACKAGE_PIN J15 [get_ports SW[0]]
set_property PACKAGE_PIN L16 [get_ports SW[1]]
set_property PACKAGE_PIN M13 [get_ports SW[2]]
set_property PACKAGE_PIN R15 [get_ports SW[3]]
set_property PACKAGE_PIN R17 [get_ports SW[4]]
set_property PACKAGE_PIN T18 [get_ports SW[5]]
set_property PACKAGE_PIN U18 [get_ports SW[6]]
set_property PACKAGE_PIN R13 [get_ports SW[7]]
set_property PACKAGE_PIN T8 [get_ports SW[8]]
set_property PACKAGE_PIN U8 [get_ports SW[9]]
set_property PACKAGE_PIN R16 [get_ports SW[10]]
set_property PACKAGE_PIN T13 [get_ports SW[11]]
set_property PACKAGE_PIN H6 [get_ports SW[12]]
set_property PACKAGE_PIN U12 [get_ports SW[13]]
set_property PACKAGE_PIN U11 [get_ports SW[14]]
set_property PACKAGE_PIN V10 [get_ports SW[15]]
#led
set_property PACKAGE_PIN H17	[get_ports led[0]] 
set_property PACKAGE_PIN K15	[get_ports led[1]] 
set_property PACKAGE_PIN J13	[get_ports led[2]] 
set_property PACKAGE_PIN N14	[get_ports led[3]] 
set_property PACKAGE_PIN R18	[get_ports led[4]] 
set_property PACKAGE_PIN V17	[get_ports led[5]] 
set_property PACKAGE_PIN U17	[get_ports led[6]] 
set_property PACKAGE_PIN U16	[get_ports led[7]] 
set_property PACKAGE_PIN V16	[get_ports led[8]] 
set_property PACKAGE_PIN T15	[get_ports led[9]] 
set_property PACKAGE_PIN U14	[get_ports led[10]] 
set_property PACKAGE_PIN T16	[get_ports led[11]] 
set_property PACKAGE_PIN V15	[get_ports led[12]] 
set_property PACKAGE_PIN V14	[get_ports led[13]] 
set_property PACKAGE_PIN V12	[get_ports led[14]] 
set_property PACKAGE_PIN V11	[get_ports led[15]] 

set_property PACKAGE_PIN N17 [get_ports OK_button]
set_property PACKAGE_PIN P17 [get_ports LEFT_button]
set_property PACKAGE_PIN M17 [get_ports RIGHT_button]
set_property PACKAGE_PIN M18 [get_ports UP_button]
set_property PACKAGE_PIN P18 [get_ports DOWN_button]
set_property PACKAGE_PIN E3 [get_ports EXT_OSC]
set_property PACKAGE_PIN C12 [get_ports RST_button]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets OK_button_IBUF]

set_property IOSTANDARD LVCMOS33 [get_ports -of_objects [get_iobanks -filter { BANK_TYPE !~  "BT_MGT" }]]
set_property IOSTANDARD LVCMOS33 [get_ports CA]
set_property IOSTANDARD LVCMOS33 [get_ports CB]
set_property IOSTANDARD LVCMOS33 [get_ports CC]
set_property IOSTANDARD LVCMOS33 [get_ports CD]
set_property IOSTANDARD LVCMOS33 [get_ports CE]
set_property IOSTANDARD LVCMOS33 [get_ports CF]
set_property IOSTANDARD LVCMOS33 [get_ports CG]
set_property IOSTANDARD LVCMOS33 [get_ports DP]

set_property IOSTANDARD LVCMOS33 [get_ports OK_button]
set_property IOSTANDARD LVCMOS33 [get_ports LEFT_button]
set_property IOSTANDARD LVCMOS33 [get_ports RIGHT_button]

set_property IOSTANDARD LVCMOS33 [get_ports {AN[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports EXT_OSC]
set_property IOSTANDARD LVCMOS33 [get_ports RST_button]
#switch
set_property IOSTANDARD LVCMOS33 [get_ports SW[0]]
set_property IOSTANDARD LVCMOS33 [get_ports SW[1]]
set_property IOSTANDARD LVCMOS33 [get_ports SW[2]]
set_property IOSTANDARD LVCMOS33 [get_ports SW[3]]
set_property IOSTANDARD LVCMOS33 [get_ports SW[4]]
set_property IOSTANDARD LVCMOS33 [get_ports SW[5]]
set_property IOSTANDARD LVCMOS33 [get_ports SW[6]]
set_property IOSTANDARD LVCMOS33 [get_ports SW[7]]
set_property IOSTANDARD LVCMOS18 [get_ports SW[8]]
set_property IOSTANDARD LVCMOS18 [get_ports SW[9]]
set_property IOSTANDARD LVCMOS33 [get_ports SW[10]]
set_property IOSTANDARD LVCMOS33 [get_ports SW[11]]
set_property IOSTANDARD LVCMOS33 [get_ports SW[12]]
set_property IOSTANDARD LVCMOS33 [get_ports SW[13]]
set_property IOSTANDARD LVCMOS33 [get_ports SW[14]]
set_property IOSTANDARD LVCMOS33 [get_ports SW[15]]
#led
set_property IOSTANDARD LVCMOS33 [get_ports led[0]]
set_property IOSTANDARD LVCMOS33 [get_ports led[1]]
set_property IOSTANDARD LVCMOS33 [get_ports led[2]]
set_property IOSTANDARD LVCMOS33 [get_ports led[3]]
set_property IOSTANDARD LVCMOS33 [get_ports led[4]]
set_property IOSTANDARD LVCMOS33 [get_ports led[5]]
set_property IOSTANDARD LVCMOS33 [get_ports led[6]]
set_property IOSTANDARD LVCMOS33 [get_ports led[7]]
set_property IOSTANDARD LVCMOS33 [get_ports led[8]]
set_property IOSTANDARD LVCMOS33 [get_ports led[9]]
set_property IOSTANDARD LVCMOS33 [get_ports led[10]]
set_property IOSTANDARD LVCMOS33 [get_ports led[11]]
set_property IOSTANDARD LVCMOS33 [get_ports led[12]]
set_property IOSTANDARD LVCMOS33 [get_ports led[13]]
set_property IOSTANDARD LVCMOS33 [get_ports led[14]]
set_property IOSTANDARD LVCMOS33 [get_ports led[15]]
##Omnidirectional Microphone

#set_property -dict { PACKAGE_PIN J5    IOSTANDARD LVCMOS33 } [get_ports { M_CLK }]; #IO_25_35 Sch=m_clk
#set_property -dict { PACKAGE_PIN H5    IOSTANDARD LVCMOS33 } [get_ports { M_DATA }]; #IO_L24N_T3_35 Sch=m_data
#set_property -dict { PACKAGE_PIN F5    IOSTANDARD LVCMOS33 } [get_ports { M_LRSEL }]; #IO_0_35 Sch=m_lrsel


##PWM Audio Amplifier

#set_property -dict { PACKAGE_PIN A11   IOSTANDARD LVCMOS33 } [get_ports { AUD_PWM }]; #IO_L4N_T0_15 Sch=aud_pwm
#set_property -dict { PACKAGE_PIN D12 IOSTANDARD LVCMOS33 } [get_ports { AUD_SD }]; #IO_L6P_T0_15 Sch=aud_sd

#ddr port
#set_property INTERNAL_VREF 0.9 [get_iobanks 34]
#set_property PACKAGE_PIN R7 [get_ports ddr2_dq[0]]                               
#set_property PACKAGE_PIN V6 [get_ports ddr2_dq[1]]                                                      
#set_property PACKAGE_PIN R8 [get_ports ddr2_dq[2]]                                                        
#set_property PACKAGE_PIN U7 [get_ports ddr2_dq[3]]                                                        
#set_property PACKAGE_PIN V7 [get_ports ddr2_dq[4]]                                                        
#set_property PACKAGE_PIN R6 [get_ports ddr2_dq[5]]                                                         
#set_property PACKAGE_PIN U6 [get_ports ddr2_dq[6]]                                                         
#set_property PACKAGE_PIN R5 [get_ports ddr2_dq[7]]                                                        
#set_property PACKAGE_PIN T5 [get_ports ddr2_dq[8]]                                                         
#set_property PACKAGE_PIN U3 [get_ports ddr2_dq[9]]                                                         
#set_property PACKAGE_PIN V5 [get_ports ddr2_dq[10]]                                                        
#set_property PACKAGE_PIN U4 [get_ports ddr2_dq[11]]                                                        
#set_property PACKAGE_PIN V4 [get_ports ddr2_dq[12]]                                                       
#set_property PACKAGE_PIN T4 [get_ports ddr2_dq[13]]                                                        
#set_property PACKAGE_PIN V1 [get_ports ddr2_dq[14]]                                                        
#set_property PACKAGE_PIN T3 [get_ports ddr2_dq[15]]                                                        
#set_property PACKAGE_PIN T6 [get_ports ddr2_dm[0]]                                                     
#set_property PACKAGE_PIN U1 [get_ports ddr2_dm[1]]                                                      
#set_property PACKAGE_PIN U9 [get_ports ddr2_dqs_p[0]]                                                      
#set_property PACKAGE_PIN V9 [get_ports ddr2_dqs_n[0]]                                                      
#set_property PACKAGE_PIN U2 [get_ports ddr2_dqs_p[1]]                                                      
#set_property PACKAGE_PIN V2 [get_ports ddr2_dqs_n[1]]                                                      
#set_property PACKAGE_PIN N6 [get_ports ddr2_addr[12]]                                                      
#set_property PACKAGE_PIN K5 [get_ports ddr2_addr[11]]                                                      
#set_property PACKAGE_PIN R2 [get_ports ddr2_addr[10]]                                                      
#set_property PACKAGE_PIN N5 [get_ports ddr2_addr[9] ]                                                      
#set_property PACKAGE_PIN L4 [get_ports ddr2_addr[8] ]                                                      
#set_property PACKAGE_PIN N1 [get_ports ddr2_addr[7] ]                                                     
#set_property PACKAGE_PIN M2 [get_ports ddr2_addr[6] ]                                                      
#set_property PACKAGE_PIN P5 [get_ports ddr2_addr[5] ]                                                      
#set_property PACKAGE_PIN L3 [get_ports ddr2_addr[4] ]                                                      
#set_property PACKAGE_PIN T1 [get_ports ddr2_addr[3] ]                                                      
#set_property PACKAGE_PIN M6 [get_ports ddr2_addr[2] ]                                                      
#set_property PACKAGE_PIN P4 [get_ports ddr2_addr[1] ]                                                      
#set_property PACKAGE_PIN M4 [get_ports ddr2_addr[0] ]                                                      
#set_property PACKAGE_PIN R1 [get_ports ddr2_ba[2]   ]                                                      
#set_property PACKAGE_PIN P3 [get_ports ddr2_ba[1]   ]                                                      
#set_property PACKAGE_PIN P2 [get_ports ddr2_ba[0]   ]                                                      
#set_property PACKAGE_PIN L6 [get_ports ddr2_ck_p[0] ]                                                      
#set_property PACKAGE_PIN L5 [get_ports ddr2_ck_n[0] ]                                                      
#set_property PACKAGE_PIN N4 [get_ports ddr2_ras_n   ]                                                      
#set_property PACKAGE_PIN L1 [get_ports ddr2_cas_n   ]                                                      
#set_property PACKAGE_PIN N2 [get_ports ddr2_we_n    ]                                                      
#set_property PACKAGE_PIN M1 [get_ports ddr2_cke[0]  ]                                                      
#set_property PACKAGE_PIN M3 [get_ports ddr2_odt[0]  ]                                                      
#set_property PACKAGE_PIN K6 [get_ports ddr2_cs_n[0] ]                     
#set_property     IOSTANDARD SSTL18_II      [get_ports  ddr2_dq[0]           ]                                                  
#set_property     IOSTANDARD SSTL18_II      [get_ports  ddr2_dq[1]           ]                                                  
#set_property     IOSTANDARD SSTL18_II      [get_ports  ddr2_dq[2]           ]                                                  
#set_property     IOSTANDARD SSTL18_II      [get_ports  ddr2_dq[3]           ]                                                  
#set_property     IOSTANDARD SSTL18_II      [get_ports  ddr2_dq[4]           ]                                                  
#set_property     IOSTANDARD SSTL18_II      [get_ports  ddr2_dq[5]           ]                                                 
#set_property     IOSTANDARD SSTL18_II      [get_ports  ddr2_dq[6]           ]                                                 
#set_property     IOSTANDARD SSTL18_II      [get_ports  ddr2_dq[7]           ]                                                  
#set_property     IOSTANDARD SSTL18_II      [get_ports  ddr2_dq[8]           ]                                                 
#set_property     IOSTANDARD SSTL18_II      [get_ports  ddr2_dq[9]           ]                                                 
#set_property     IOSTANDARD SSTL18_II      [get_ports  ddr2_dq[10]          ]                                                 
#set_property     IOSTANDARD SSTL18_II      [get_ports  ddr2_dq[11]          ]                                                 
#set_property     IOSTANDARD SSTL18_II      [get_ports  ddr2_dq[12]          ]                                                  
#set_property     IOSTANDARD SSTL18_II      [get_ports  ddr2_dq[13]          ]                                                  
#set_property     IOSTANDARD SSTL18_II      [get_ports  ddr2_dq[14]          ]                                                  
#set_property     IOSTANDARD SSTL18_II      [get_ports  ddr2_dq[15]          ]                                                  
#set_property     IOSTANDARD SSTL18_II      [get_ports  ddr2_dm[0]           ]                                                  
#set_property     IOSTANDARD SSTL18_II      [get_ports  ddr2_dm[1]           ]                                                  
#set_property     IOSTANDARD DIFF_SSTL18_II [get_ports  ddr2_dqs_p[0]        ]                                                  
#set_property     IOSTANDARD DIFF_SSTL18_II [get_ports  ddr2_dqs_n[0]        ]                                                  
#set_property     IOSTANDARD DIFF_SSTL18_II [get_ports  ddr2_dqs_p[1]        ]                                                  
#set_property     IOSTANDARD DIFF_SSTL18_II [get_ports  ddr2_dqs_n[1]        ]                                                  
#set_property     IOSTANDARD SSTL18_II      [get_ports  ddr2_addr[12]        ]                                                  
#set_property     IOSTANDARD SSTL18_II      [get_ports  ddr2_addr[11]        ]                                                 
#set_property     IOSTANDARD SSTL18_II      [get_ports  ddr2_addr[10]        ]                                                 
#set_property     IOSTANDARD SSTL18_II      [get_ports  ddr2_addr[9]         ]                                                  
#set_property     IOSTANDARD SSTL18_II      [get_ports  ddr2_addr[8]         ]                                                  
#set_property     IOSTANDARD SSTL18_II      [get_ports  ddr2_addr[7]         ]                                                  
#set_property     IOSTANDARD SSTL18_II      [get_ports  ddr2_addr[6]         ]                                                 
#set_property     IOSTANDARD SSTL18_II      [get_ports  ddr2_addr[5]         ]                                                 
#set_property     IOSTANDARD SSTL18_II      [get_ports  ddr2_addr[4]         ]                                                  
#set_property     IOSTANDARD SSTL18_II      [get_ports  ddr2_addr[3]         ]                                                 
#set_property     IOSTANDARD SSTL18_II      [get_ports  ddr2_addr[2]         ]                                                  
#set_property     IOSTANDARD SSTL18_II      [get_ports  ddr2_addr[1]         ]                                                  
#set_property     IOSTANDARD SSTL18_II      [get_ports  ddr2_addr[0]         ]                                                  
#set_property     IOSTANDARD SSTL18_II      [get_ports  ddr2_ba[2]           ]                                                  
#set_property     IOSTANDARD SSTL18_II      [get_ports  ddr2_ba[1]           ]                                                  
#set_property     IOSTANDARD SSTL18_II      [get_ports  ddr2_ba[0]           ]                                                 
#set_property     IOSTANDARD DIFF_SSTL18_II [get_ports  ddr2_ck_p[0]         ]                                                  
#set_property     IOSTANDARD DIFF_SSTL18_II [get_ports  ddr2_ck_n[0]         ]                                                  
#set_property     IOSTANDARD SSTL18_II      [get_ports  ddr2_ras_n           ]                                                  
#set_property     IOSTANDARD SSTL18_II      [get_ports  ddr2_cas_n           ]                                                 
#set_property     IOSTANDARD SSTL18_II      [get_ports  ddr2_we_n            ]                                                 
#set_property     IOSTANDARD SSTL18_II      [get_ports  ddr2_cke[0]          ]                                                  
#set_property     IOSTANDARD SSTL18_II      [get_ports  ddr2_odt[0]          ]                                                  
#set_property     IOSTANDARD SSTL18_II      [get_ports  ddr2_cs_n[0]         ]                                                                         

create_clock -period 10.000 -name CLK -waveform {0.000 5.000} [get_ports EXT_OSC]
set_property SEVERITY {Warning} [get_drc_checks NSTD-1]

