# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/xilinx_project/git_project/projet_CPU/projet_CPU/project_4/project_4.cache/wt [current_project]
set_property parent.project_path C:/xilinx_project/git_project/projet_CPU/projet_CPU/project_4/project_4.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/xilinx_project/git_project/projet_CPU/projet_CPU/project_4/project_4.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/xilinx_project/git_project/projet_CPU/projet_CPU/src/CPU_package.vhd
  C:/xilinx_project/git_project/projet_CPU/projet_CPU/src/Clock_manager.vhd
  C:/xilinx_project/git_project/projet_CPU/projet_CPU/src/Freq_Divider.vhd
  C:/xilinx_project/git_project/projet_CPU/projet_CPU/src/arbitrated_mem_controller.vhd
  C:/xilinx_project/git_project/projet_CPU/projet_CPU/src/ddram_controller.vhd
  C:/xilinx_project/git_project/projet_CPU/projet_CPU/src/main.vhd
  C:/xilinx_project/git_project/projet_CPU/projet_CPU/src/physical_controller.vhd
  C:/xilinx_project/git_project/projet_CPU/projet_CPU/src/switch_manager.vhd
}
read_vhdl -vhdl2008 -library xil_defaultlib {
  C:/xilinx_project/git_project/projet_CPU/projet_CPU/src/io_mem_controller.vhd
  C:/xilinx_project/git_project/projet_CPU/projet_CPU/src/main_interconnect.vhd
}
read_ip -quiet c:/xilinx_project/git_project/projet_CPU/projet_CPU/project_4/project_4.srcs/sources_1/ip/mig_7series_0/mig_7series_0.xci
set_property used_in_implementation false [get_files -all c:/xilinx_project/git_project/projet_CPU/projet_CPU/project_4/project_4.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/constraints/mig_7series_0.xdc]
set_property used_in_implementation false [get_files -all c:/xilinx_project/git_project/projet_CPU/projet_CPU/project_4/project_4.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/constraints/mig_7series_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/xilinx_project/git_project/projet_CPU/projet_CPU/const/const.xdc
set_property used_in_implementation false [get_files C:/xilinx_project/git_project/projet_CPU/projet_CPU/const/const.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top main_interconnect -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef main_interconnect.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file main_interconnect_utilization_synth.rpt -pb main_interconnect_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
