# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/xilinx_project/git_project/projet_CPU/projet_CPU/test_project/project_base_2017/project_base_2017.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.xci
# IP: The module: 'dist_mem_gen_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/xilinx_project/git_project/projet_CPU/projet_CPU/test_project/project_base_2017/project_base_2017.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dist_mem_gen_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/xilinx_project/git_project/projet_CPU/projet_CPU/test_project/project_base_2017/project_base_2017.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.xci
# IP: The module: 'dist_mem_gen_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/xilinx_project/git_project/projet_CPU/projet_CPU/test_project/project_base_2017/project_base_2017.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dist_mem_gen_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
