# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/my_lib/Nexys-4-DDR-Master.xdc

# Block Designs: bd/test_cache/test_cache.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_cache || ORIG_REF_NAME==test_cache} -quiet] -quiet

# IP: bd/test_cache/ip/test_cache_Cache_bus_M_to_S_0_0/test_cache_Cache_bus_M_to_S_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_cache_Cache_bus_M_to_S_0_0 || ORIG_REF_NAME==test_cache_Cache_bus_M_to_S_0_0} -quiet] -quiet

# IP: bd/test_cache/ip/test_cache_Cache_bus_M_to_S_peer_0_1/test_cache_Cache_bus_M_to_S_peer_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_cache_Cache_bus_M_to_S_peer_0_1 || ORIG_REF_NAME==test_cache_Cache_bus_M_to_S_peer_0_1} -quiet] -quiet

# XDC: bd/test_cache/test_cache_ooc.xdc
