# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/my_lib/Nexys-4-DDR-Master.xdc

# Block Designs: bd/test_cache/test_cache.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_cache || ORIG_REF_NAME==test_cache} -quiet] -quiet

# IP: bd/test_cache/ip/test_cache_Cache_bus_M_to_S_0_0/test_cache_Cache_bus_M_to_S_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_cache_Cache_bus_M_to_S_0_0 || ORIG_REF_NAME==test_cache_Cache_bus_M_to_S_0_0} -quiet] -quiet

# IP: bd/test_cache/ip/test_cache_Cache_bus_M_to_S_peer_0_0/test_cache_Cache_bus_M_to_S_peer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_cache_Cache_bus_M_to_S_peer_0_0 || ORIG_REF_NAME==test_cache_Cache_bus_M_to_S_peer_0_0} -quiet] -quiet

# IP: bd/test_cache/ip/test_cache_clk_wiz_2/test_cache_clk_wiz_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_cache_clk_wiz_2 || ORIG_REF_NAME==test_cache_clk_wiz_2} -quiet] -quiet

# XDC: bd/test_cache/ip/test_cache_clk_wiz_2/test_cache_clk_wiz_2_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==test_cache_clk_wiz_2 || ORIG_REF_NAME==test_cache_clk_wiz_2} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/test_cache/ip/test_cache_clk_wiz_2/test_cache_clk_wiz_2.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==test_cache_clk_wiz_2 || ORIG_REF_NAME==test_cache_clk_wiz_2} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/test_cache/ip/test_cache_clk_wiz_2/test_cache_clk_wiz_2_ooc.xdc

# XDC: bd/test_cache/test_cache_ooc.xdc
